"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import ErrorState from "@/components/ui/ErrorState";
import LoadingState from "@/components/ui/LoadingState";
import PageHeader from "@/components/ui/PageHeader";
import { getApiErrorMessage, recruitmentApi } from "@/lib/api";
import type { RecruitmentApplication } from "@/types/recruitment";

export default function NewInterviewPage() {
  const router = useRouter(); const [apps, setApps] = useState<RecruitmentApplication[] | null>(null); const [form, setForm] = useState({ application: "", scheduled_at: "", duration_minutes: "60", interview_type: "", location_or_link: "", notes: "" }); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { recruitmentApi.listApplications({ status: "ACTIVE", page_size: 100 }).then((data) => setApps(data.results)).catch((caught) => setError(getApiErrorMessage(caught))); }, []);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.application || !form.scheduled_at || saving) { setError("Application and scheduled time are required."); return; } setSaving(true); setError(null); try { await recruitmentApi.createInterview({ ...form, scheduled_at: new Date(form.scheduled_at).toISOString(), duration_minutes: Number(form.duration_minutes) }); router.push("/recruitment/interviews"); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setSaving(false); } };
  if (!apps) return error ? <ErrorState message={error} /> : <LoadingState />; return <div className="space-y-6"><PageHeader title="Schedule Interview" description="Create a scheduled interview for an active application." /><form onSubmit={submit} className="space-y-5 rounded-2xl border border-slate-200 bg-white p-6"><label className="block"><span className="mb-1.5 block text-sm font-medium">Application</span><select value={form.application} onChange={(event) => setForm((current) => ({ ...current, application: event.target.value }))} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Select application</option>{apps.map((app) => <option key={app.id} value={app.id}>Application {app.id.slice(0, 8)}</option>)}</select></label><div className="grid gap-5 md:grid-cols-2"><label><span className="mb-1.5 block text-sm font-medium">Scheduled time</span><input type="datetime-local" value={form.scheduled_at} onChange={(event) => setForm((current) => ({ ...current, scheduled_at: event.target.value }))} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /></label><label><span className="mb-1.5 block text-sm font-medium">Duration (minutes)</span><input type="number" min="1" value={form.duration_minutes} onChange={(event) => setForm((current) => ({ ...current, duration_minutes: event.target.value }))} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /></label></div><label className="block"><span className="mb-1.5 block text-sm font-medium">Interview type</span><input value={form.interview_type} onChange={(event) => setForm((current) => ({ ...current, interview_type: event.target.value }))} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /></label><label className="block"><span className="mb-1.5 block text-sm font-medium">Location or meeting link</span><input value={form.location_or_link} onChange={(event) => setForm((current) => ({ ...current, location_or_link: event.target.value }))} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /></label>{error && <ErrorState message={error} />}<div className="flex justify-end gap-3"><Link href="/recruitment/interviews" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium">Cancel</Link><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white">{saving ? "Scheduling…" : "Schedule Interview"}</button></div></form></div>;
}
