# Generated by Django 5.2.17 on 2026-10-09 22:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0009_concept_profile_fields'),
        ('institutions', '0043_institution_website_employee_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=30)),
                ('respondent_description', models.CharField(blank=True, help_text='Who the complaint is about when they are not an employee (a contractor, a customer).', max_length=200)),
                ('category', models.CharField(choices=[('HARASSMENT', 'Harassment (including sexual harassment)'), ('BULLYING', 'Bullying or intimidation'), ('DISCRIMINATION', 'Discrimination'), ('MISCONDUCT', 'Misconduct or unethical behaviour'), ('HEALTH_SAFETY', 'Health and safety'), ('PAY_BENEFITS', 'Pay, allowances or benefits'), ('WORKING_CONDITIONS', 'Working conditions or hours'), ('MANAGEMENT', 'Management or supervision'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('incident_location', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under review'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', max_length=15)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=10)),
                ('resolution', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_assigned', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints_filed', to='employees.employee')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='institutions.institution')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('respondent', models.ForeignKey(blank=True, help_text='The colleague the complaint is about, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_received', to='employees.employee')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ComplaintNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField()),
                ('is_internal', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='complaints.complaint')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutions.institution')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['institution', 'status'], name='complaints__institu_5273bf_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['assigned_to', 'status'], name='complaints__assigne_2cfd47_idx'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.UniqueConstraint(fields=('institution', 'code'), name='uniq_complaint_code'),
        ),
    ]
