"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import ErrorState from "@/components/ui/ErrorState";
import PageHeader from "@/components/ui/PageHeader";
import { getApiErrorMessage, recruitmentApi } from "@/lib/api";

export default function NewCandidatePage() {
  const router = useRouter(); const [form, setForm] = useState({ first_name: "", middle_name: "", last_name: "", email: "", phone: "", source: "", notes: "" }); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const update = (field: keyof typeof form, value: string) => setForm((current) => ({ ...current, [field]: value }));
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!form.first_name.trim() || !form.last_name.trim() || !form.email.trim() || saving) { setError("First name, last name, and email are required."); return; } setSaving(true); setError(null); try { const candidate = await recruitmentApi.createCandidate({ ...form, first_name: form.first_name.trim(), middle_name: form.middle_name.trim(), last_name: form.last_name.trim(), email: form.email.trim(), phone: form.phone.trim(), source: form.source.trim(), notes: form.notes.trim() }); router.push(`/recruitment/candidates/${candidate.id}`); } catch (caught) { setError(getApiErrorMessage(caught)); } finally { setSaving(false); } };
  return <div className="space-y-6"><PageHeader title="New Candidate" description="Create a tenant-scoped candidate profile before creating an application." /><form onSubmit={submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-6"><div className="grid gap-5 md:grid-cols-2">{[["First Name", "first_name", true], ["Middle Name", "middle_name", false], ["Last Name", "last_name", true], ["Email", "email", true], ["Phone", "phone", false], ["Source", "source", false]].map(([label, field, required]) => <label key={String(field)} className="block"><span className="mb-1.5 block text-sm font-medium">{label}{required ? " *" : ""}</span><input type={field === "email" ? "email" : "text"} value={form[field as keyof typeof form]} onChange={(event) => update(field as keyof typeof form, event.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /></label>)}<label className="md:col-span-2"><span className="mb-1.5 block text-sm font-medium">Notes</span><textarea rows={5} value={form.notes} onChange={(event) => update("notes", event.target.value)} className="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /></label></div>{error && <ErrorState message={error} />}<div className="flex justify-end gap-3"><Link href="/recruitment/candidates" className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium">Cancel</Link><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{saving ? "Creating…" : "Create Candidate"}</button></div></form></div>;
}
