"use client";
import Link from "next/link";
import { useCallback } from "react";
import { BriefcaseBusiness, CalendarDays, FileCheck2, UsersRound } from "lucide-react";
import ErrorState from "@/components/ui/ErrorState";
import KPIStatCard from "@/components/ui/KPIStatCard";
import PageHeader from "@/components/ui/PageHeader";
import { dashboardsApi } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
export default function RecruitmentDashboardPage() { const load = useCallback(() => dashboardsApi.getRecruitmentDashboard(), []); const { data, loading, error, reload } = useApiResource(load); const max = Math.max(...(data?.pipeline.map((item) => item.count) ?? [1]), 1); return <main className="space-y-6"><PageHeader title="Recruitment Dashboard" description="Server-owned hiring pipeline and open-role activity." actions={<Link href="/recruitment/job-postings" className="rounded-xl bg-violet-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-violet-800">Manage openings</Link>} />{error && <ErrorState message={error} onRetry={reload} />}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><KPIStatCard title="Open jobs" value={data?.open_jobs ?? "—"} icon={<BriefcaseBusiness className="h-5 w-5" />} /><KPIStatCard title="Active candidates" value={data?.active_candidates ?? "—"} icon={<UsersRound className="h-5 w-5" />} /><KPIStatCard title="Applications" value={data?.applications ?? "—"} icon={<FileCheck2 className="h-5 w-5" />} /><KPIStatCard title="Interviews scheduled" value={data?.scheduled_interviews ?? "—"} icon={<CalendarDays className="h-5 w-5" />} /><KPIStatCard title="Offers extended" value={data?.offers_extended ?? "—"} icon={<FileCheck2 className="h-5 w-5" />} /></div><section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="font-semibold text-slate-950">Pipeline by stage</h2><p className="mt-1 text-sm text-slate-500">Applications grouped by the institution-defined recruitment stage.</p>{loading ? <p className="py-10 text-center text-sm text-slate-500">Loading pipeline...</p> : <div className="mt-6 space-y-4">{data?.pipeline.map((item) => <div key={item.name}><div className="mb-1.5 flex justify-between text-sm"><span>{item.name}</span><span className="font-semibold">{item.count}</span></div><div className="h-3 rounded-full bg-slate-100"><div className="h-full rounded-full bg-violet-600" style={{ width: `${Math.max((item.count / max) * 100, item.count ? 3 : 0)}%` }} /></div></div>)}{!data?.pipeline.length && <p className="text-sm text-slate-500">No active pipeline stages are configured.</p>}</div>}</section></main>; }
