"use client";

import { useCallback, useMemo, useState } from "react";
import Link from "next/link";
import { CheckCircle2, Info, ShieldCheck } from "lucide-react";

import ConfirmDialog from "@/components/ui/ConfirmDialog";
import ErrorState from "@/components/ui/ErrorState";
import LoadingState from "@/components/ui/LoadingState";
import PageHeader from "@/components/ui/PageHeader";
import { accountingApi, getApiErrorMessage, institutionsApi } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
import type { AccountingConfiguration, AccountingConfigurationPayload, AccountingSetupChoice } from "@/types/accounting";

type FormState = Pick<AccountingConfigurationPayload, "base_currency" | "reporting_framework" | "tax_identification_number" | "vat_registered" | "is_vat_withholding_agent" | "fiscal_year_start_month">;

function initialForm(configuration: AccountingConfiguration | null, currency: string): FormState {
  return { base_currency: configuration?.base_currency ?? currency, reporting_framework: configuration?.reporting_framework ?? "", tax_identification_number: configuration?.tax_identification_number ?? "", vat_registered: configuration?.vat_registered ?? false, is_vat_withholding_agent: configuration?.is_vat_withholding_agent ?? false, fiscal_year_start_month: configuration?.fiscal_year_start_month ?? 1 };
}

export default function GhanaAccountingSetupPage() {
  const load = useCallback(async () => Promise.all([accountingApi.listAccountingConfigurations(), accountingApi.getAccountingSetupChoices(), institutionsApi.getCurrentInstitution()]), []);
  const { data, loading, error, reload } = useApiResource(load);
  const [selectedId, setSelectedId] = useState(""); const [draft, setDraft] = useState<Partial<FormState>>({}); const [confirmingPreset, setConfirmingPreset] = useState<AccountingSetupChoice | null>(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [actionError, setActionError] = useState("");
  const configuration = data?.[0].results[0] ?? null; const choices = data?.[1]; const institution = data?.[2].institution; const institutionType = institution?.institution_type;
  const recommended = useMemo(() => choices?.choices.find((choice) => choice.mode === "PRESET" && choice.institution_type === institutionType) ?? null, [choices, institutionType]);
  const activeSelectedId = selectedId || configuration?.selected_accounting_preset_version || recommended?.preset_version_id || ""; const selected = choices?.choices.find((choice) => choice.preset_version_id === activeSelectedId) ?? null; const appliedPreset = configuration?.accounting_setup_mode === "PRESET"; const form = { ...initialForm(configuration, choices?.currency ?? ""), ...draft };

  const saveCustom = async () => {
    if (!choices) return;
    setSaving(true); setActionError(""); setMessage("");
    const payload: AccountingConfigurationPayload = { country_code: choices.country_code, base_currency: form.base_currency.toUpperCase(), accounting_setup_mode: "CUSTOM", selected_accounting_preset_version: null, reporting_framework: form.reporting_framework, tax_identification_number: form.tax_identification_number, vat_registered: form.vat_registered, is_vat_withholding_agent: form.is_vat_withholding_agent, statutory_profile_metadata: configuration?.statutory_profile_metadata ?? {}, fiscal_year_start_month: Number(form.fiscal_year_start_month), is_configured: true };
    try { if (configuration) await accountingApi.updateAccountingConfiguration(configuration.id, payload); else await accountingApi.createAccountingConfiguration(payload); setMessage("Custom accounting configuration saved."); reload(); } catch (caught) { setActionError(getApiErrorMessage(caught)); } finally { setSaving(false); }
  };
  const applyPreset = async () => {
    if (!confirmingPreset?.preset_version_id) return;
    setSaving(true); setActionError(""); setMessage("");
    try {
      const result = await accountingApi.applyAccountingPreset(confirmingPreset.preset_version_id, { base_currency: form.base_currency.toUpperCase(), fiscal_year_start_month: Number(form.fiscal_year_start_month), ...(confirmingPreset.coa_templates?.[0] ? { coa_template: confirmingPreset.coa_templates[0].id } : {}) });
      setMessage(confirmingPreset.name + " applied. " + result.created_count + " chart account" + (result.created_count === 1 ? "" : "s") + " created; " + result.reused_count + " reused.");
      setConfirmingPreset(null); reload();
    } catch (caught) { setActionError(getApiErrorMessage(caught)); setConfirmingPreset(null); } finally { setSaving(false); }
  };

  if (loading && !data) return <LoadingState />;
  if (error && !data) return <div><ErrorState title="Unable to load accounting setup" message={error} onRetry={reload} /></div>;
  if (!choices || !institution) return <div><ErrorState title="Accounting setup unavailable" message="Institution configuration choices are unavailable." onRetry={reload} /></div>;

  return <div className="mx-auto max-w-6xl space-y-6">
    <PageHeader title="Accounting Setup" description="Review the active accounting configuration or deliberately apply a supported preset." actions={<Link href="/accounting/reports" className="inline-flex rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-800 hover:bg-slate-50">Open accounting reports</Link>} />
    {error && <ErrorState message={error} onRetry={reload} />}{actionError && <p role="alert" className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{actionError}</p>}{message && <p className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800"><CheckCircle2 className="h-5 w-5" />{message}</p>}
    {recommended && !appliedPreset && <section className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Optional recommendation</p><h2 className="mt-1 font-semibold text-emerald-950">{recommended.name}</h2><p className="mt-1 text-sm text-emerald-800">This matches the institution classification of {institutionType?.replaceAll("_", " ").toLowerCase()}. It is not selected or applied automatically.</p></section>}
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex gap-3"><span className="rounded-xl bg-slate-100 p-2.5 text-slate-700"><Info className="h-5 w-5" /></span><div><h2 className="font-semibold text-slate-950">Configuration details</h2><p className="mt-1 text-sm text-slate-500">Country is sourced from the institution. Updating a country elsewhere never changes this base currency automatically.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Field label="Institution country"><input value={choices.country_code} readOnly className="w-full rounded-xl border bg-slate-50 px-3 py-2.5 text-sm" /></Field><Field label="Base currency"><input value={form.base_currency} onChange={(event) => setDraft({ ...form, base_currency: event.target.value.toUpperCase() })} maxLength={3} disabled={appliedPreset} className="w-full rounded-xl border px-3 py-2.5 text-sm disabled:bg-slate-50" /></Field><Field label="Fiscal year starts"><select value={form.fiscal_year_start_month} onChange={(event) => setDraft({ ...form, fiscal_year_start_month: Number(event.target.value) })} disabled={appliedPreset} className="w-full rounded-xl border px-3 py-2.5 text-sm disabled:bg-slate-50">{Array.from({ length: 12 }, (_, index) => <option key={index + 1} value={index + 1}>Month {index + 1}</option>)}</select></Field><Field label="Reporting framework"><input value={form.reporting_framework} onChange={(event) => setDraft({ ...form, reporting_framework: event.target.value })} placeholder="Required for custom setup" disabled={appliedPreset} className="w-full rounded-xl border px-3 py-2.5 text-sm disabled:bg-slate-50" /></Field><Field label="Tax identification number"><input value={form.tax_identification_number} onChange={(event) => setDraft({ ...form, tax_identification_number: event.target.value })} disabled={appliedPreset} className="w-full rounded-xl border px-3 py-2.5 text-sm disabled:bg-slate-50" /></Field><div className="flex flex-col justify-end gap-3 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={form.vat_registered} onChange={(event) => setDraft({ ...form, vat_registered: event.target.checked })} disabled={appliedPreset} />VAT registered</label><label className="flex items-center gap-2"><input type="checkbox" checked={form.is_vat_withholding_agent} onChange={(event) => setDraft({ ...form, is_vat_withholding_agent: event.target.checked })} disabled={appliedPreset} />VAT withholding agent</label></div></div></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div className="flex gap-3"><span className="rounded-xl bg-emerald-50 p-2.5 text-emerald-700"><ShieldCheck className="h-5 w-5" /></span><div><h2 className="font-semibold text-slate-950">Supported setup choices</h2><p className="mt-1 text-sm text-slate-500">Preset application creates the backend-controlled chart template. An applied preset cannot be switched from this screen.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{choices.choices.map((choice) => { const key = choice.preset_version_id ?? choice.mode; const isApplied = choice.preset_version_id === configuration?.selected_accounting_preset_version || (choice.mode === "CUSTOM" && configuration?.accounting_setup_mode === "CUSTOM"); const isSelected = choice.preset_version_id === activeSelectedId; const isRecommended = choice.preset_version_id === recommended?.preset_version_id; const cardClass = isApplied ? "border-slate-900 bg-slate-50" : isSelected ? "border-emerald-400 bg-emerald-50" : "hover:border-slate-300"; return <button type="button" key={key} disabled={Boolean(appliedPreset) || choice.mode === "CUSTOM"} onClick={() => setSelectedId(choice.preset_version_id ?? "")} className={"rounded-xl border p-4 text-left transition " + cardClass + " disabled:cursor-default disabled:opacity-80"}><p className="font-semibold text-slate-950">{choice.preset_code ? choice.preset_code + " " + (choice.version_code ?? "") : choice.name}</p><p className="mt-1 text-sm text-slate-500">{choice.name}</p>{isApplied && <p className="mt-2 text-xs font-semibold text-slate-700">Currently applied</p>}{isRecommended && !isApplied && <p className="mt-2 text-xs font-semibold text-emerald-700">Recommended for institution type</p>}{choice.reporting_framework && <p className="mt-2 text-xs text-slate-600">Framework: {choice.reporting_framework}</p>}{choice.compliance_warning && <p className="mt-2 text-xs text-amber-700">{choice.compliance_warning}</p>}</button>; })}</div></section>
    {!appliedPreset && <div className="flex flex-wrap justify-end gap-3"><button type="button" disabled={saving || !form.reporting_framework.trim()} onClick={() => void saveCustom()} className="rounded-xl border border-slate-300 px-4 py-2.5 text-sm font-semibold text-slate-800 disabled:cursor-not-allowed disabled:opacity-50">{saving ? "Saving…" : "Save custom configuration"}</button><button type="button" disabled={saving || !selected} onClick={() => setConfirmingPreset(selected)} className="rounded-xl bg-slate-900 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">{saving ? "Applying…" : "Review and apply preset"}</button></div>}
    {appliedPreset && <p className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-600">This institution already has an applied preset. Preset migration requires an explicit governed workflow and is intentionally not simulated here.</p>}
    <ConfirmDialog open={Boolean(confirmingPreset)} title="Apply accounting preset?" description={(confirmingPreset?.name ?? "This preset") + " will instantiate its server-controlled chart template for " + institution.name + ". This action is recorded and cannot be silently reversed."} confirmLabel="Apply preset" loading={saving} onCancel={() => setConfirmingPreset(null)} onConfirm={() => void applyPreset()} />
  </div>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="text-sm font-medium text-slate-800">{label}</span><span className="mt-1 block">{children}</span></label>; }
