"use client";

import { useCallback } from "react";
import ErrorState from "@/components/ui/ErrorState";
import PageHeader from "@/components/ui/PageHeader";
import { accountingApi } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";

export default function GhanaAccountingSetupPage() {
  const load = useCallback(async () => Promise.all([accountingApi.listAccountingConfigurations(), accountingApi.getAccountingSetupChoices()]), []); const { data, loading, error, reload } = useApiResource(load); if (loading) return <main className="p-6 text-sm text-slate-500">Loading accounting setup...</main>; if (error || !data) return <main className="p-6"><ErrorState title="Unable to load accounting setup" message={error ?? "Configuration is unavailable."} onRetry={reload} /></main>; const [configurations, choices] = data; const configuration = configurations.results[0] ?? null;
  return <main className="space-y-6"><PageHeader title="Ghana Accounting Setup" description="Review the institution's accounting localisation configuration." /><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Available Setup Choices</h2><p className="mt-1 text-sm text-slate-500">Options are supplied by the backend for this institution; no Ghana preset is hardcoded in the frontend.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{choices.choices.map((choice) => { const selected = choice.preset_version_id === configuration?.selected_accounting_preset_version || (choice.mode === "CUSTOM" && configuration?.accounting_setup_mode === "CUSTOM"); return <div key={choice.preset_version_id ?? choice.mode} className={`rounded-xl border p-4 ${selected ? "border-slate-900 bg-slate-50" : ""}`}><p className="font-semibold">{choice.preset_code ? `${choice.preset_code} ${choice.version_code ?? ""}` : choice.name}</p><p className="mt-1 text-xs text-slate-500">{choice.name}</p>{choice.reporting_framework && <p className="mt-2 text-xs text-slate-600">Framework: {choice.reporting_framework}</p>}{choice.compliance_warning && <p className="mt-2 text-xs text-amber-700">{choice.compliance_warning}</p>}</div>; })}</div></section><section className="rounded-2xl border bg-white p-5"><h2 className="font-semibold">Current Configuration</h2>{configuration ? <div className="mt-5 grid gap-4 md:grid-cols-2"><Item label="Country / currency" value={`${configuration.country_code} / ${configuration.base_currency}`} /><Item label="Setup mode" value={configuration.accounting_setup_mode} /><Item label="Reporting framework" value={configuration.reporting_framework} /><Item label="Fiscal year start" value={`Month ${configuration.fiscal_year_start_month}`} /><Item label="VAT registered" value={configuration.vat_registered ? "Yes" : "No"} /><Item label="Configured" value={configuration.is_configured ? "Yes" : "No"} /></div> : <p className="mt-3 text-sm text-slate-500">No accounting configuration has been saved for this institution.</p>}</section><div className="rounded-2xl border bg-slate-50 p-4 text-sm text-slate-600">Statutory calculations and compliance logic remain backend-controlled. Saving or changing this configuration requires the full statutory-profile form and is not simulated here.</div></main>;
}
function Item({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
