import Link from "next/link";
import { ArrowRight, Mail, ShieldCheck } from "lucide-react";

const steps = [
  ["Receive an invitation", "Your Super Admin, Institution Admin, or HR team sends an invitation to your work email."],
  ["Create your account", "Open the secure link in the email and set your password."],
  ["Sign in", "Return to ErgonX and access the workspace assigned to your role."],
];

export default function GetStartedPage() {
  return <main className="min-h-screen bg-slate-50 px-5 py-8 text-slate-950 sm:px-8 sm:py-12"><div className="mx-auto max-w-3xl"><Link href="/login" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600 transition hover:text-slate-950">← Back to sign in</Link><section className="mt-6 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl shadow-slate-200/60"><div className="bg-slate-950 px-7 py-8 text-white sm:px-10"><p className="text-sm font-semibold tracking-[0.17em] text-sky-300">GET STARTED</p><h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Get your ErgonX account.</h1><p className="mt-3 max-w-xl text-slate-300">ErgonX accounts are created through a secure invitation. It takes just a few steps.</p></div><div className="p-7 sm:p-10"><div className="space-y-6">{steps.map(([title, description], index) => <div key={title} className="flex gap-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-sky-50 text-sm font-bold text-sky-700">{index + 1}</span><div><h2 className="font-semibold text-slate-950">{title}</h2><p className="mt-1 text-sm leading-6 text-slate-600">{description}</p></div></div>)}</div><div className="mt-8 rounded-2xl border border-sky-100 bg-sky-50 p-5"><div className="flex gap-3"><Mail className="mt-0.5 h-5 w-5 shrink-0 text-sky-700" /><div><p className="font-semibold text-slate-950">Need an invitation?</p><p className="mt-1 text-sm leading-6 text-slate-600">Contact your organization&apos;s administrator. New organizations must be invited by an ErgonX Super Admin.</p></div></div></div><div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p className="flex items-center gap-2 text-sm text-slate-500"><ShieldCheck className="h-4 w-4 text-emerald-600" />Invitation links are secure and single-use.</p><Link href="/login" className="inline-flex items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800">Go to sign in <ArrowRight className="h-4 w-4" /></Link></div></div></section></div></main>;
}
