"use client";

import { useCallback, useState } from "react";
import ErrorState from "@/components/ui/ErrorState";
import LoadingState from "@/components/ui/LoadingState";
import PageHeader from "@/components/ui/PageHeader";
import StatusBadge from "@/components/ui/StatusBadge";
import { getApiErrorMessage, recruitmentApi } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";

export default function RecruitmentStagesPage() {
  const load = useCallback(() => recruitmentApi.listRecruitmentStages({ ordering: "sequence" }), []); const { data, loading, error, reload } = useApiResource(load); const [form, setForm] = useState({ name: "", sequence: "", is_terminal: false }); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState<string | null>(null);
  const create = async (event: React.FormEvent) => { event.preventDefault(); if (!form.name.trim() || !form.sequence || saving) { setSaveError("Stage name and sequence are required."); return; } setSaving(true); setSaveError(null); try { await recruitmentApi.createRecruitmentStage({ name: form.name.trim(), sequence: Number(form.sequence), is_terminal: form.is_terminal, is_active: true }); setForm({ name: "", sequence: "", is_terminal: false }); reload(); } catch (caught) { setSaveError(getApiErrorMessage(caught)); } finally { setSaving(false); } };
  if (loading) return <LoadingState />; if (error || !data) return <ErrorState message={error ?? "Unable to load recruitment stages."} onRetry={reload} />;
  return <div className="space-y-6"><PageHeader title="Recruitment Stages" description="The ordered, institution-scoped stages used by the recruitment pipeline." /><form onSubmit={create} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 md:grid-cols-[1fr_150px_auto_auto]"><input value={form.name} onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} placeholder="Stage name" className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /><input type="number" min="1" value={form.sequence} onChange={(event) => setForm((current) => ({ ...current, sequence: event.target.value }))} placeholder="Sequence" className="rounded-lg border border-slate-300 px-3 py-2.5 text-sm" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.is_terminal} onChange={(event) => setForm((current) => ({ ...current, is_terminal: event.target.checked }))} /> Terminal</label><button disabled={saving} className="rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{saving ? "Adding…" : "Add Stage"}</button>{saveError && <p className="text-sm text-red-600 md:col-span-4">{saveError}</p>}</form><div className="rounded-2xl border border-slate-200 bg-white"><div className="divide-y divide-slate-100">{data.results.length === 0 ? <p className="p-6 text-sm text-slate-500">No stages are configured. Applications cannot be submitted until an active stage exists.</p> : data.results.map((stage) => <div key={stage.id} className="flex items-center gap-4 p-5"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-slate-100 text-sm font-semibold">{stage.sequence}</span><div className="min-w-0 flex-1"><p className="font-medium text-slate-900">{stage.name}</p><p className="mt-0.5 text-xs text-slate-500">{stage.is_terminal ? "Terminal stage" : "Active workflow stage"}</p></div><StatusBadge status={stage.is_active ? "ACTIVE" : "INACTIVE"} /><button type="button" onClick={async () => { try { await recruitmentApi.updateRecruitmentStage(stage.id, { is_active: !stage.is_active }); reload(); } catch (caught) { setSaveError(getApiErrorMessage(caught)); } }} className="text-sm font-medium text-slate-600">{stage.is_active ? "Deactivate" : "Activate"}</button></div>)}</div></div></div>;
}
