"use client";

import { useParams, useRouter } from "next/navigation";
import { useCallback, useState } from "react";
import ConfirmDialog from "@/components/ui/ConfirmDialog";
import BackNavigation from "@/components/ui/BackNavigation";
import ErrorState from "@/components/ui/ErrorState";
import LoadingState from "@/components/ui/LoadingState";
import PageHeader from "@/components/ui/PageHeader";
import StatusBadge from "@/components/ui/StatusBadge";
import { getApiErrorMessage, recruitmentApi } from "@/lib/api";
import { useApiResource } from "@/lib/useApiResource";
import { buttonClasses } from "@/components/ui/Button";

type Action = "extend" | "accept" | "decline" | "withdraw" | "hire" | null;
export default function OfferDetailPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const load = useCallback(() => recruitmentApi.getOffer(id), [id]); const { data, loading, error, reload } = useApiResource(load); const [action, setAction] = useState<Action>(null); const [employeeNumber, setEmployeeNumber] = useState(""); const [saving, setSaving] = useState(false); const [actionError, setActionError] = useState<string | null>(null);
  const run = async () => { if (!action) return; if (action === "hire" && !employeeNumber.trim()) { setActionError("Employee number is required to hire."); setAction(null); return; } setSaving(true); setActionError(null); try { if (action === "hire") { const employee = await recruitmentApi.hireOfferCandidate(id, employeeNumber.trim()); router.push(`/hr/employees/${employee.employee_id}`); return; } await recruitmentApi.offerAction(id, action); setAction(null); reload(); } catch (caught) { setActionError(getApiErrorMessage(caught)); setAction(null); } finally { setSaving(false); } };
  if (loading) return <LoadingState />; if (error || !data) return <ErrorState message={error ?? "Offer not found."} onRetry={reload} />; const available = data.status === "DRAFT" ? ["extend", "withdraw"] : data.status === "EXTENDED" ? ["accept", "decline", "withdraw"] : data.status === "ACCEPTED" && !data.hired_employee ? ["hire"] : [];
  return <div className="space-y-6"><BackNavigation fallback="/recruitment/offers" label="Back to offers" /><PageHeader title="Offer" description={`Proposed start: ${data.proposed_start_date}`} actions={<StatusBadge status={data.status} />}/>{actionError && <ErrorState message={actionError} />}<div className="rounded-2xl border border-line bg-surface p-6"><dl className="grid gap-5 sm:grid-cols-2"><div><dt className="text-xs uppercase text-ink-muted">Employment type</dt><dd className="mt-1 font-medium">{data.employment_type}</dd></div><div><dt className="text-xs uppercase text-ink-muted">Compensation</dt><dd className="mt-1 font-medium">{data.base_salary ? `${data.currency} ${data.base_salary}` : "Not set"}</dd></div><div className="sm:col-span-2"><dt className="text-xs uppercase text-ink-muted">Terms</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{data.terms || "No terms recorded."}</dd></div></dl><div className="mt-6 flex flex-wrap gap-2">{available.map((item) => <button key={item} onClick={() => setAction(item as Action)} className={`rounded-lg px-4 py-2 text-sm font-medium ${item === "withdraw" || item === "decline" ? "bg-danger text-white" : "bg-primary text-white"}`}>{item === "hire" ? "Hire Candidate" : item[0].toUpperCase() + item.slice(1)}</button>)}</div></div><ConfirmDialog open={action !== null && action !== "hire"} title="Confirm offer action?" description="This action follows the backend offer workflow." confirmLabel="Confirm" destructive={action === "withdraw" || action === "decline"} loading={saving} onConfirm={() => void run()} onCancel={() => setAction(null)} />{action === "hire" && <div className="fixed inset-0 z-[101] flex items-center justify-center bg-overlay p-4"><div className="w-full max-w-md rounded-2xl bg-surface p-6"><h2 className="font-semibold">Hire candidate</h2><p className="mt-1 text-sm text-ink-muted">This creates the employee and onboarding record through the backend.</p><input value={employeeNumber} onChange={(event) => setEmployeeNumber(event.target.value)} placeholder="Employee number" className="mt-4 w-full h-9 rounded-lg border border-line-strong px-3" /><div className="mt-5 flex justify-end gap-3"><button onClick={() => setAction(null)} className="text-sm text-ink-muted">Cancel</button><button disabled={saving || !employeeNumber.trim()} onClick={() => void run()} className={buttonClasses({ variant: "primary" })}>{saving ? "Hiring…" : "Hire"}</button></div></div></div>}</div>;
}
