"use client";

import { FileBarChart } from "lucide-react";
import { useCallback, useMemo, useState } from "react";
import ErrorState from "@/components/ui/ErrorState";
import PageHeader from "@/components/ui/PageHeader";
import { accountingApi } from "@/lib/api";
import { formatAmount } from "@/lib/format";
import { useApiResource } from "@/lib/useApiResource";

export default function AccountingReportsPage() {
  const [dateFrom, setDateFrom] = useState(""); const [dateTo, setDateTo] = useState(""); const [applied, setApplied] = useState({ date_from: "", date_to: "" });
  const load = useCallback(() => accountingApi.getTrialBalance({ date_from: applied.date_from || undefined, date_to: applied.date_to || undefined }), [applied]); const { data, loading, error, reload } = useApiResource(load); const rows = useMemo(() => data?.rows ?? [], [data]);
  return <main className="space-y-6"><PageHeader title="Financial Reports" description="Filterable, permission-aware accounting reports for the active institution." /><div className="grid gap-4 md:grid-cols-3"><ReportCard title="Trial Balance" description="Debit and credit balances across posted accounts." active /><ReportCard title="Income Statement" description="Available from the backend and scheduled for the next report view." /><ReportCard title="Balance Sheet" description="Available from the backend and scheduled for the next report view." /></div><section className="rounded-2xl border bg-white p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><h2 className="font-semibold">Trial Balance</h2><p className="text-sm text-slate-500">Derived from posted journal lines by the backend.</p></div><div className="flex flex-wrap gap-2"><input type="date" value={dateFrom} onChange={(event) => setDateFrom(event.target.value)} className="rounded-xl border p-2 text-sm" /><input type="date" value={dateTo} onChange={(event) => setDateTo(event.target.value)} className="rounded-xl border p-2 text-sm" /><button type="button" onClick={() => setApplied({ date_from: dateFrom, date_to: dateTo })} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Apply</button></div></div>{error && <div className="mt-4"><ErrorState message={error} onRetry={reload} /></div>}<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="border-b text-left text-xs uppercase text-slate-500"><th className="pb-3">Account</th><th className="pb-3">Type</th><th className="pb-3">Debit</th><th className="pb-3">Credit</th></tr></thead><tbody>{rows.map((row) => <tr key={row.account_id} className="border-b last:border-0"><td className="py-4"><span className="font-medium">{row.code}</span><span className="ml-3">{row.name}</span></td><td className="py-4">{row.account_type}</td><td className="py-4">{formatAmount(row.debit)}</td><td className="py-4">{formatAmount(row.credit)}</td></tr>)}</tbody></table>{loading && <p className="py-10 text-center text-sm text-slate-500">Loading trial balance...</p>}{!loading && !rows.length && <p className="py-10 text-center text-sm text-slate-500">No posted account balances found for this period.</p>}</div>{data && <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Total Debit" value={formatAmount(data.total_debit)} /><Metric label="Total Credit" value={formatAmount(data.total_credit)} /><Metric label="Status" value={data.balanced ? "Balanced" : "Out of balance"} /></div>}</section></main>;
}
function ReportCard({ title, description, active = false }: { title: string; description: string; active?: boolean }) { return <div className={`rounded-2xl border bg-white p-5 ${active ? "border-slate-900" : "opacity-70"}`}><div className="w-fit rounded-xl bg-slate-100 p-3"><FileBarChart className="h-5 w-5" /></div><h2 className="mt-4 font-semibold">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-500">{description}</p></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
